# NakuNode-Prompter for ComfyUI
# Integration of multiple prompt generation and guidance systems

# Removed WAN22 nodes
WAN22_NODE_CLASS_MAPPINGS = {}
WAN22_NODE_DISPLAY_NAME_MAPPINGS = {}
WAN22_AVAILABLE = False

try:
    from .nodes.NAKUNode_Flux_QwenEdit_Prompt import NODE_CLASS_MAPPINGS as KONTEXT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as KONTEXT_NODE_DISPLAY_NAME_MAPPINGS
    KONTEXT_AVAILABLE = True
except ImportError as e:
    print(f"[NakuNode-Prompter] Warning: Could not import Kontext nodes: {e}")
    KONTEXT_NODE_CLASS_MAPPINGS = {}
    KONTEXT_NODE_DISPLAY_NAME_MAPPINGS = {}
    KONTEXT_AVAILABLE = False

try:
    from .nodes.NakuNode_nag import NODE_CLASS_MAPPINGS as NAG_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NAG_NODE_DISPLAY_NAME_MAPPINGS
    NAG_AVAILABLE = True
except ImportError as e:
    print(f"[NakuNode-Prompter] Warning: Could not import NAG nodes: {e}")
    NAG_NODE_CLASS_MAPPINGS = {}
    NAG_NODE_DISPLAY_NAME_MAPPINGS = {}
    NAG_AVAILABLE = False

try:
    from .nodes.image_video_prompt_optimizer import NODE_CLASS_MAPPINGS as IMG_OPTIMIZER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMG_OPTIMIZER_NODE_DISPLAY_NAME_MAPPINGS
    IMG_OPTIMIZER_AVAILABLE = True
except ImportError as e:
    print(f"[NakuNode-Prompter] Warning: Could not import Image Video Prompt Optimizer nodes: {e}")
    IMG_OPTIMIZER_NODE_CLASS_MAPPINGS = {}
    IMG_OPTIMIZER_NODE_DISPLAY_NAME_MAPPINGS = {}
    IMG_OPTIMIZER_AVAILABLE = False

try:
    from .nodes.professional_video_prompt_generator import NODE_CLASS_MAPPINGS as PROFESSIONAL_VIDEO_PROMPT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROFESSIONAL_VIDEO_PROMPT_NODE_DISPLAY_NAME_MAPPINGS
    PROFESSIONAL_VIDEO_PROMPT_AVAILABLE = True
except ImportError as e:
    print(f"[NakuNode-Prompter] Warning: Could not import Professional Video Prompt Generator nodes: {e}")
    PROFESSIONAL_VIDEO_PROMPT_NODE_CLASS_MAPPINGS = {}
    PROFESSIONAL_VIDEO_PROMPT_NODE_DISPLAY_NAME_MAPPINGS = {}
    PROFESSIONAL_VIDEO_PROMPT_AVAILABLE = False

try:
    from .nodes.dual_image_video_script_generator import NODE_CLASS_MAPPINGS as DUAL_IMAGE_SCRIPT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DUAL_IMAGE_SCRIPT_NODE_DISPLAY_NAME_MAPPINGS
    DUAL_IMAGE_SCRIPT_AVAILABLE = True
except ImportError as e:
    print(f"[NakuNode-Prompter] Warning: Could not import Dual Image Video Script Generator nodes: {e}")
    DUAL_IMAGE_SCRIPT_NODE_CLASS_MAPPINGS = {}
    DUAL_IMAGE_SCRIPT_NODE_DISPLAY_NAME_MAPPINGS = {}
    DUAL_IMAGE_SCRIPT_AVAILABLE = False

try:
    from .nodes.storyboard_image_generator import NODE_CLASS_MAPPINGS as STORYBOARD_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS
    STORYBOARD_AVAILABLE = True
except ImportError as e:
    print(f"[NakuNode-Prompter] Warning: Could not import Storyboard Image Generator nodes: {e}")
    STORYBOARD_NODE_CLASS_MAPPINGS = {}
    STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS = {}
    STORYBOARD_AVAILABLE = False

try:
    from .nodes.NakuNode_TextEditor import NODE_CLASS_MAPPINGS as TEXT_EDITOR_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_EDITOR_NODE_DISPLAY_NAME_MAPPINGS
    TEXT_EDITOR_AVAILABLE = True
except ImportError as e:
    print(f"[NakuNode-Prompter] Warning: Could not import Text Editor nodes: {e}")
    TEXT_EDITOR_NODE_CLASS_MAPPINGS = {}
    TEXT_EDITOR_NODE_DISPLAY_NAME_MAPPINGS = {}
    TEXT_EDITOR_AVAILABLE = False

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(WAN22_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(KONTEXT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NAG_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMG_OPTIMIZER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PROFESSIONAL_VIDEO_PROMPT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DUAL_IMAGE_SCRIPT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(STORYBOARD_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXT_EDITOR_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(WAN22_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(KONTEXT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(NAG_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMG_OPTIMIZER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PROFESSIONAL_VIDEO_PROMPT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DUAL_IMAGE_SCRIPT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_EDITOR_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']

# Print version and capability information
print("NakuNode Promt Generator V1.0 Dev ------------------A professional promts generator for WAN / Qwen / Flux")

# Print summary of available nodes
print(f"[NakuNode-Prompter] Loaded {len(NODE_CLASS_MAPPINGS)} total nodes")
if KONTEXT_AVAILABLE:
    print(f"[NakuNode-Prompter] Kontext nodes available: {list(KONTEXT_NODE_CLASS_MAPPINGS.keys())}")
if NAG_AVAILABLE:
    print(f"[NakuNode-Prompter] NAG nodes available: {list(NAG_NODE_CLASS_MAPPINGS.keys())}")
if STORYBOARD_AVAILABLE:
    print(f"[NakuNode-Prompter] Storyboard nodes available: {list(STORYBOARD_NODE_CLASS_MAPPINGS.keys())}")
if TEXT_EDITOR_AVAILABLE:
    print(f"[NakuNode-Prompter] Text Editor nodes available: {list(TEXT_EDITOR_NODE_CLASS_MAPPINGS.keys())}")